version: "3"

volumes:
  web_data:
  db_data:

services:
  web:
    image: nginx:alpine
    depends_on:
      - wordpress
      - database
    volumes:
      - ./configs/nginx/sites-enabled/:/etc/nginx/conf.d/:ro
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt/etc/live/${DOMAIN?No domain set}/:/var/certs/:ro
      - "web_data:/usr/share/nginx/html/:ro"
    ports:
      - "${IP:-0.0.0.0}:80:80/tcp"
      - "${IP:-0.0.0.0}:443:443/tcp"

  wordpress:
    image: wordpress:php7.1-fpm-alpine
    volumes:
      - "web_data:/var/www/html/:rw"
    environment:
      - "WORDPRESS_DB_HOST=database"
      - "WORDPRESS_DB_USER=${SQL_USER:-wordpress}"
      - "WORDPRESS_DB_PASSWORD=${SQL_PASSWORD:-password}"
      - "WORDPRESS_DB_NAME=${SQL_DATABASE_NAME:-wordpress}"

  database:
    image: mysql:8
    volumes: 
      - "db_data:/var/lib/mysql:rw"
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_USER=${SQL_USER:-wordpress}"
      - "MYSQL_PASSWORD=${SQL_PASSWORD:-password}"
      - "MYSQL_DATABASE=${SQL_DATABASE_NAME:-wordpress}"